--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015-11-20 5:02:23 PM
-- Server version: 5.6.27-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE mydb;

--
-- Definition for table `inventory items`
--
DROP TABLE IF EXISTS `inventory items`;
CREATE TABLE `inventory items` (
  inventorynum INT(32) NOT NULL,
  name VARCHAR(45) DEFAULT NULL,
  price FLOAT DEFAULT 0,
  quantity INT(11) DEFAULT NULL,
  PRIMARY KEY (inventorynum)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table department
--
DROP TABLE IF EXISTS department;
CREATE TABLE department (
  number INT(11) NOT NULL,
  name VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (number)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table interclubteam
--
DROP TABLE IF EXISTS interclubteam;
CREATE TABLE interclubteam (
  level FLOAT NOT NULL DEFAULT 2,
  captainID INT(11) DEFAULT NULL,
  `co-captainID` INT(11) DEFAULT NULL,
  PRIMARY KEY (level)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table member
--
DROP TABLE IF EXISTS member;
CREATE TABLE member (
  memberID INT(11) NOT NULL,
  rating VARCHAR(45) DEFAULT NULL,
  phonenumber VARCHAR(45) DEFAULT NULL,
  firstname VARCHAR(45) DEFAULT NULL,
  middlename VARCHAR(45) DEFAULT NULL,
  lastname VARCHAR(45) DEFAULT NULL,
  renewaldate DATE DEFAULT NULL,
  streetname VARCHAR(45) DEFAULT NULL,
  streetnum VARCHAR(45) DEFAULT NULL,
  datejoined DATE DEFAULT NULL,
  postalCode VARCHAR(10) DEFAULT NULL,
  city VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (memberID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 606
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table social_event
--
DROP TABLE IF EXISTS social_event;
CREATE TABLE social_event (
  eventname VARCHAR(25) NOT NULL,
  eventdate DATE DEFAULT NULL,
  membersOnly TINYINT(1) DEFAULT 0,
  PRIMARY KEY (eventname)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table tournament
--
DROP TABLE IF EXISTS tournament;
CREATE TABLE tournament (
  eventname VARCHAR(45) NOT NULL,
  eventdate DATE NOT NULL DEFAULT '1900-01-01',
  winnerid VARCHAR(45) DEFAULT NULL,
  prize FLOAT DEFAULT 100,
  draw INT(3) DEFAULT 64,
  PRIMARY KEY (eventname, eventdate)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table boardmember
--
DROP TABLE IF EXISTS boardmember;
CREATE TABLE boardmember (
  positionType VARCHAR(45) NOT NULL,
  email VARCHAR(45) DEFAULT NULL,
  posHeldSince VARCHAR(45) DEFAULT NULL,
  deptManaged INT(11) DEFAULT NULL,
  PRIMARY KEY (positionType),
  INDEX deptManaged_idx (deptManaged),
  CONSTRAINT number FOREIGN KEY (deptManaged)
    REFERENCES department(number) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AVG_ROW_LENGTH = 1489
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table employee
--
DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
  id INT(11) NOT NULL,
  role VARCHAR(45) DEFAULT NULL,
  phonenum VARCHAR(15) DEFAULT NULL,
  email VARCHAR(45) DEFAULT NULL,
  startdate DATE DEFAULT NULL,
  hours FLOAT DEFAULT 0,
  wage FLOAT DEFAULT 10,
  firstname VARCHAR(45) DEFAULT NULL,
  middlename VARCHAR(45) DEFAULT NULL,
  lastname VARCHAR(45) DEFAULT NULL,
  streetnum VARCHAR(7) DEFAULT NULL,
  postalcode VARCHAR(10) DEFAULT NULL,
  streetname VARCHAR(45) DEFAULT NULL,
  city VARCHAR(45) DEFAULT NULL,
  supervisorID INT(11) DEFAULT NULL,
  dept INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX number_idx (dept),
  CONSTRAINT department FOREIGN KEY (dept)
    REFERENCES department(number) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table event
--
DROP TABLE IF EXISTS event;
CREATE TABLE event (
  name VARCHAR(25) NOT NULL,
  date DATE NOT NULL DEFAULT '1900-01-01',
  minlimit INT(11) NOT NULL DEFAULT 1,
  maxlimit INT(11) DEFAULT 1,
  budget DECIMAL(2, 0) DEFAULT NULL,
  fee DECIMAL(2, 0) DEFAULT NULL,
  dept INT(11) DEFAULT NULL,
  PRIMARY KEY (name, date),
  INDEX controllingDept_idx (dept),
  CONSTRAINT controllingDept FOREIGN KEY (dept)
    REFERENCES department(number) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table juniormember
--
DROP TABLE IF EXISTS juniormember;
CREATE TABLE juniormember (
  birthdate DATE DEFAULT NULL,
  juniorMemberId INT(11) NOT NULL,
  PRIMARY KEY (juniorMemberId),
  CONSTRAINT memberID FOREIGN KEY (juniorMemberId)
    REFERENCES member(memberID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table guardian
--
DROP TABLE IF EXISTS guardian;
CREATE TABLE guardian (
  firstname VARCHAR(45) NOT NULL,
  middlename VARCHAR(45) DEFAULT NULL,
  lastname VARCHAR(45) DEFAULT NULL,
  streetnum VARCHAR(6) DEFAULT NULL,
  streetname VARCHAR(45) DEFAULT NULL,
  postalcode VARCHAR(10) DEFAULT NULL,
  city VARCHAR(45) DEFAULT NULL,
  juniorid INT(11) DEFAULT NULL,
  PRIMARY KEY (firstname),
  INDEX juniorMemberId_idx (juniorid),
  CONSTRAINT juniorMemberId FOREIGN KEY (juniorid)
    REFERENCES juniormember(juniorMemberId) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table pro
--
DROP TABLE IF EXISTS pro;
CREATE TABLE pro (
  email VARCHAR(45) NOT NULL,
  rate FLOAT DEFAULT NULL,
  phonenumber VARCHAR(15) DEFAULT NULL,
  firstname VARCHAR(45) DEFAULT NULL,
  lastname VARCHAR(45) DEFAULT NULL,
  middlename VARCHAR(45) DEFAULT NULL,
  hiredBy1 VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (email),
  INDEX Interviewer_idx (hiredBy1),
  CONSTRAINT Interviewer FOREIGN KEY (hiredBy1)
    REFERENCES boardmember(positionType) ON DELETE NO ACTION ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table `inventory items`
--

-- Table mydb.`inventory items` does not contain any data (it is empty)

-- 
-- Dumping data for table department
--

-- Table mydb.department does not contain any data (it is empty)

-- 
-- Dumping data for table interclubteam
--

-- Table mydb.interclubteam does not contain any data (it is empty)

-- 
-- Dumping data for table member
--
INSERT INTO member VALUES
(1, '2', '(529) 762-2353', 'Barclay', 'Ori', 'Horn', '2005-01-01', 'Ap #829-5933 Enim. Ave', '1019', '2000-01-01', '50715', 'Flinu'),
(2, '2', '(150) 595-5029', 'Xenos', 'Gay', 'Lindsay', '2005-01-01', '351 Id Avenue', '3643', '2000-01-01', '41004', 'Irvine'),
(6, '4', '(776) 210-9362', 'Camille', 'Joel', 'Ramsey', '2005-01-01', 'Ap #689-7278 Magna Av.', '4531', '2000-01-01', '03-410', 'Ajmer'),
(8, '5', '(745) 134-3574', 'Jacqueline', 'Summer', 'Rodriquez', '2005-01-01', '5134 Ut Rd.', '2850', '2000-01-01', '46-377', 'Loverval'),
(10, '6', '(940) 552-8790', 'Jena', 'Donovan', 'Trevino', '2005-01-01', 'Ap #150-2911 Praesent Ave', '4840', '2000-01-01', '69517', 'Lavoir'),
(11, '2', '(907) 666-5037', 'Bevis', 'Hollee', 'Bean', '2005-01-01', '6299 Consequat Street', '889', '2000-01-01', '5662SM', 'S'),
(13, '2', '(698) 641-4361', 'Timon', 'Mikayla', 'Romero', '2005-01-01', '3310 Massa. Rd.', '4998', '2000-01-01', '388973', 'Castel Baronia'),
(14, '5', '(615) 316-9282', 'Xerxes', 'Richard', 'Fowler', '2005-01-01', 'Ap #894-9733 Lacus. Rd.', '2555', '2000-01-01', '62-084', 'Gujrat'),
(15, '2', '(136) 869-9576', 'Donna', 'Beau', 'Garner', '2005-01-01', '1459 Tincidunt Av.', '226', '2000-01-01', 'M4K 7Y2', 'Malartic'),
(16, '5', '(756) 217-3645', 'Keegan', 'Larissa', 'Wiggins', '2005-01-01', 'Ap #934-4010 Condimentum. St.', '604', '2000-01-01', '31410', 'skenderun'),
(17, '4', '(859) 379-0712', 'Imani', 'Christian', 'Miller', '2005-01-01', '509-9982 Neque. Av.', '999', '2000-01-01', '91301', 'Bendigo'),
(18, '6', '(412) 362-2333', 'Guinevere', 'Hadley', 'Pace', '2005-01-01', 'Ap #180-7055 Cursus St.', '163', '2000-01-01', '1655', 'Thiaumont'),
(19, '3', '(494) 579-7627', 'Callie', 'Galena', 'Holman', '2005-01-01', 'Ap #449-7026 Egestas Road', '2101', '2000-01-01', '28023', 'Neeroeteren'),
(20, '3', '(724) 302-1388', 'Imelda', 'Zoe', 'Mcguire', '2005-01-01', '381-1325 Integer Rd.', '1759', '2000-01-01', '78406', 'Wolkrange'),
(23, '4', '(805) 717-3567', 'Maris', 'Yolanda', 'Black', '2005-01-01', '949-1724 Per Av.', '2232', '2000-01-01', '71313', 'Corroy-le-Grand'),
(24, '5', '(241) 311-9666', 'Natalie', 'Victor', 'Bernard', '2005-01-01', '375-8680 In Road', '162', '2000-01-01', '38813', 'Hamoir'),
(26, '5', '(351) 320-6559', 'Kenyon', 'Illiana', 'Morales', '2005-01-01', '804-2680 Aenean St.', '374', '2000-01-01', '51937', 'Ipatinga'),
(28, '4', '(852) 143-9007', 'Yolanda', 'Sacha', 'Barrett', '2005-01-01', '3870 Faucibus Road', '1679', '2000-01-01', '3218DQ', 'Mesoraca'),
(29, '5', '(899) 870-8230', 'Christine', 'Len', 'Harrington', '2005-01-01', 'Ap #720-6647 Nulla St.', '3633', '2000-01-01', '7287SE', 'New Plymouth'),
(30, '3', '(743) 347-5405', 'Simone', 'Mallory', 'Warner', '2005-01-01', '884-3474 Eu Av.', '3221', '2000-01-01', '61146', 'Roksem'),
(31, '4', '(774) 151-5729', 'Tanya', 'Upton', 'Chan', '2005-01-01', '4810 Aliquet St.', '3602', '2000-01-01', '6106', 'Barddhaman'),
(33, '4', '(603) 337-4481', 'Jorden', 'Armando', 'Reyes', '2005-01-01', '486-5144 Est. Av.', '3538', '2000-01-01', '87238', 'Saint Andr?'),
(38, '2', '(956) 200-6792', 'Wyoming', 'Kessie', 'Sawyer', '2005-01-01', '656-9647 Aenean Ave', '1875', '2000-01-01', 'L3V 4Y1', 'Heerlen'),
(39, '5', '(623) 853-1539', 'Russell', 'Melvin', 'Green', '2005-01-01', '2055 Nulla Street', '3421', '2000-01-01', '54056', 'Saint Paul'),
(40, '5', '(334) 158-4774', 'Simon', 'Emily', 'Clark', '2005-01-01', '210-1806 Dictum Rd.', '2890', '2000-01-01', '4634', 'Westmeerbeek'),
(41, '3', '(142) 969-3947', 'Kaye', 'Laith', 'Wilder', '2005-01-01', '2929 Mollis Street', '2412', '2000-01-01', '8566', 'Suru'),
(1234, '5.0', '403-835-1552', 'Mike', NULL, 'Simister', '2015-10-10', 'mystreeet', '1235', '2015-10-10', 'b1b-1b1', 'Calgary');

-- 
-- Dumping data for table social_event
--

-- Table mydb.social_event does not contain any data (it is empty)

-- 
-- Dumping data for table tournament
--

-- Table mydb.tournament does not contain any data (it is empty)

-- 
-- Dumping data for table boardmember
--
INSERT INTO boardmember VALUES
('', '', '', NULL),
('Assistant Social Director', 'assistant social director@tennisclub.com', '2015-06-01', NULL),
('Assistant Tournament Director', 'assistant tournament director@tennisclub.com', '2016-05-09', NULL),
('Facilities Director', 'facilities director@tennisclub.com', '2016-09-05', NULL),
('Membership Director', 'membership director@tennisclub.com', '2015-10-14', NULL),
('Past President', 'past president@tennisclub.com', '2015-11-14', NULL),
('Secretary', 'secretary@tennisclub.com', '2015-06-01', NULL),
('Social Director', 'social director@tennisclub.com', '2015-10-14', NULL),
('Tournament Director', 'tournament director@tennisclub.com', '2016-10-25', NULL),
('Treasurer', 'treasurer@tennisclub.com', '2015-11-14', NULL),
('Vice-President', 'vice-president@tennisclub.com', '2016-09-05', NULL);

-- 
-- Dumping data for table employee
--

-- Table mydb.employee does not contain any data (it is empty)

-- 
-- Dumping data for table event
--

-- Table mydb.event does not contain any data (it is empty)

-- 
-- Dumping data for table juniormember
--

-- Table mydb.juniormember does not contain any data (it is empty)

-- 
-- Dumping data for table guardian
--

-- Table mydb.guardian does not contain any data (it is empty)

-- 
-- Dumping data for table pro
--

-- Table mydb.pro does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;